stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - call install_choco.bat
    - choco install nuget.commandline vswhere -y
  script:
    - nuget restore DMXforDummies.sln
    - call msbuild.bat /t:Clean,Rebuild DMXforDummies.sln /p:Configuration="Debug"
    - call msbuild.bat /t:Clean,Rebuild DMXforDummies.sln /p:Configuration="Release"
  tags:
    - msbuild
    - windows
  artifacts:
    when: on_success
    paths:
      - DMXforDummies\bin\Release
    expire_in: 14 days
    name: "%CI_BUILD_REF_SLUG%_%CI_BUILD_NAME%_%CI_BUILD_REF%"
  cache:
    key: "windows_$CI_PIPELINE_ID"
    paths:
      - packages
      - DMXforDummies\bin
      - DMXforDummies\obj

deploy-to-fs:
  stage: deploy
  tags:
    - msbuild
    - windows
  before_script:
    - call install_choco.bat
    - choco install vswhere -y
  script:
    - nuget restore DMXforDummies.sln
    - net use \\fs\Software$ %AVAdmin_PW% /user:haus.akademischerverein.de\AVAdmin
    - call msbuild.bat /t:Publish DMXforDummies.sln /p:Configuration="Release" /p:DeployOnBuild=true /p:PublishDir=\\fs\Software$\DMXforDummies\
  when: manual
  cache:
    key: "windows_$CI_PIPELINE_ID"
    paths:
      - packages
      - DMXforDummies\bin
      - DMXforDummies\obj