stages:
  - build

build:
  stage: build
  before_script:
    - 'set PATH=%PATH%;C:\Program Files (x86)\MSBuild\14.0\Bin'
  script:
    - 'C:\multirunner\nuget.exe restore DMXforDummies\DMXforDummies.sln'
    - msbuild /t:Clean,Rebuild DMXforDummies\DMXforDummies.sln /p:Configuration="Debug"
    - msbuild /t:Clean,Rebuild DMXforDummies\DMXforDummies.sln /p:Configuration="Release"
  tags:
    - vs2015
    - windows
  artifacts:
    when: on_success
    paths:
      - DMXforDummies\bin\Release
    expire_in: 14 days
    name: "%CI_BUILD_REF_SLUG%_%CI_BUILD_NAME%_%CI_BUILD_REF%"
  cache:
    key: "windows/$CI_PIPELINE_ID"
    paths:
      - packages