stages:
  - build
  - deploy

build:
  stage: build
  script:
    - dotnet restore DMXforDummies.sln
    - dotnet clean DMXforDummies.sln -c Debug
    - dotnet clean DMXforDummies.sln -c Release
    - dotnet build DMXforDummies.sln -c Debug
    - dotnet build DMXforDummies.sln -c Release
  tags:
    - msbuild
    - windows
  artifacts:
    when: on_success
    paths:
      - DMXforDummies\bin\Release
    expire_in: 14 days
    name: "%CI_BUILD_REF_SLUG%_%CI_BUILD_NAME%_%CI_BUILD_REF%"
  cache:
    key: "windows_$CI_PIPELINE_ID"
    paths:
      - packages
      - DMXforDummies\bin
      - DMXforDummies\obj

deploy-to-fs:
  stage: deploy
  tags:
    - msbuild
    - windows
  script:
    - dotnet restore DMXforDummies.sln
    - net use \\192.168.0.4\Software$ %AVAdmin_PW% /user:AV\avadmin
    - dotnet publish DMXforDummies.sln -c Release -p:DeployOnBuild=true -o \\192.168.0.4\Software$\DMXforDummies\
  when: manual
  cache:
    key: "windows_$CI_PIPELINE_ID"
    paths:
      - packages
      - DMXforDummies\bin
      - DMXforDummies\obj
