name: Build and Pack

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: dotnet/nbgv@v0.4
      id: nbgv
    - name: Build
      run: dotnet build -c Release /p:ContinuousIntegrationBuild=true
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DMXforDummies-${{ steps.nbgv.outputs.SemVer2 }}
        path: |
          DMXforDummies/bin/Release/**/*
