name: Build and Publish

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET SDK from global.json
      uses: actions/setup-dotnet@v4
    - uses: dotnet/nbgv@v0.4
      id: nbgv
    - name: Publish Windows
      run: dotnet publish DMXforDummies/DMXforDummies.csproj -c Release -r win-x64 -o output-windows/ --self-contained true
    - name: Publish Linux
      run: dotnet publish DMXforDummies/DMXforDummies.csproj -c Release -r linux-x64 -o output-linux/ --self-contained true
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DMXforDummies-${{ runner.os }}-${{ steps.nbgv.outputs.SemVer2 }}
        path: |
          output-linux/*
          output-windows/*
